import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

/* ── Section Header ────────────────────────────────────────────── */
const Section = ({ title, children }) => (
  <div className="mb-5">
    <h3 className="text-xs font-bold uppercase tracking-wider text-purple-400 mb-2">{title}</h3>
    {children}
  </div>
);

/* ── Color Swatch ──────────────────────────────────────────────── */
const ColorSwatch = ({ hex, name, usage }) => (
  <div className="flex items-center gap-2.5 mb-2">
    <div className="w-9 h-9 rounded-xl flex-shrink-0 shadow-md border border-white/10"
         style={{ backgroundColor: hex || '#7C3AED' }} />
    <div className="min-w-0">
      <p className="text-sm font-semibold truncate" style={{ color: 'var(--text-primary)' }}>
        {name}&nbsp;<span className="font-mono text-xs opacity-50">{hex}</span>
      </p>
      <p className="text-xs truncate" style={{ color: 'var(--text-muted)' }}>{usage}</p>
    </div>
  </div>
);

/* ── Programmatic PDF builder ──────────────────────────────────── */
async function buildPDF(guidelines, logo, brandContext, isDark) {
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });

  const W = pdf.internal.pageSize.getWidth();   // 595.28
  const H = pdf.internal.pageSize.getHeight();  // 841.89
  const MARGIN = 40;
  const CONTENT_W = W - (MARGIN * 2);
  let y = MARGIN;
  let pageNumber = 1;

  const brandName = brandContext?.brandName || logo?.brand_name || 'Brand';

  /* ── Theme colours ── */
  const THEME = isDark ? {
    pageBg:    [10, 10, 30],
    accent:    [124, 58, 237],
    title:     [255, 255, 255],
    body:      [200, 200, 230],
    muted:     [140, 140, 170],
    card:      [30, 30, 60],
    border:    [50, 50, 90]
  } : {
    pageBg:    [255, 255, 255],
    accent:    [124, 58, 237],
    title:     [30, 20, 70],
    body:      [60, 60, 90],
    muted:     [130, 130, 160],
    card:      [245, 245, 255],
    border:    [220, 220, 240]
  };

  /* ── Helpers ── */
  const drawPageTemplate = () => {
    pdf.setFillColor(...THEME.pageBg);
    pdf.rect(0, 0, W, H, 'F');
    // Header accent
    pdf.setFillColor(...THEME.accent);
    pdf.rect(0, 0, W, 4, 'F');
  };

  const drawFooter = () => {
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(...THEME.muted);
    pdf.text(`${brandName} — Brand Guidelines`, MARGIN, H - 20);
    pdf.text(`Page ${pageNumber}`, W - MARGIN, H - 20, { align: 'right' });
    pdf.text('Generated by BrandyBot', W / 2, H - 20, { align: 'center' });
  };

  const ensureSpace = (needed) => {
    if (y + needed > H - 60) {
      drawFooter();
      pdf.addPage();
      pageNumber++;
      drawPageTemplate();
      y = MARGIN + 20;
    }
  };

  drawPageTemplate();

  /* ── 1. COVER / HEADER ── */
  let logoImgData = null;
  if (logo?.logo_url) {
    try {
      const r = await fetch(logo.logo_url);
      const blob = await r.blob();
      logoImgData = await new Promise(res => {
        const rd = new FileReader();
        rd.onload = () => res(rd.result);
        rd.readAsDataURL(blob);
      });
    } catch (_) {}
  }

  const LOGO_BOX = 60;
  if (logoImgData) {
    pdf.addImage(logoImgData, 'PNG', MARGIN, y + 10, LOGO_BOX, LOGO_BOX, undefined, 'FAST');
  } else {
    pdf.setFillColor(...THEME.accent);
    pdf.roundedRect(MARGIN, y + 10, LOGO_BOX, LOGO_BOX, 10, 10, 'F');
  }

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(26);
  pdf.setTextColor(...THEME.title);
  pdf.text(brandName, MARGIN + LOGO_BOX + 20, y + 45);
  
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(...THEME.muted);
  pdf.text('OFFICIAL BRAND GUIDELINES', MARGIN + LOGO_BOX + 20, y + 62);
  
  y += LOGO_BOX + 40;
  pdf.setDrawColor(...THEME.border);
  pdf.line(MARGIN, y, W - MARGIN, y);
  y += 30;

  /* ── 2. COLOR PALETTE ── */
  if (guidelines.colorPalette) {
    ensureSpace(40);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(...THEME.accent);
    pdf.text('COLOR PALETTE', MARGIN, y);
    y += 20;

    const colors = Object.values(guidelines.colorPalette);
    colors.forEach(c => {
      ensureSpace(45);
      const hex = c.hex || '#000000';
      const r = parseInt(hex.slice(1, 3), 16) || 0;
      const g = parseInt(hex.slice(3, 5), 16) || 0;
      const b = parseInt(hex.slice(5, 7), 16) || 0;

      // Card
      pdf.setFillColor(...THEME.card);
      pdf.roundedRect(MARGIN, y - 10, CONTENT_W, 40, 6, 6, 'F');
      
      // Swatch
      pdf.setFillColor(r, g, b);
      pdf.roundedRect(MARGIN + 10, y - 2, 24, 24, 4, 4, 'F');
      
      // Info
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10);
      pdf.setTextColor(...THEME.title);
      pdf.text(c.name || 'Primary Color', MARGIN + 45, y + 6);
      
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(...THEME.muted);
      pdf.text(hex.toUpperCase(), MARGIN + 45, y + 18);
      
      const usageLines = pdf.splitTextToSize(c.usage || '', CONTENT_W - 160);
      pdf.text(usageLines, MARGIN + 140, y + 6);
      
      y += 45;
    });
    y += 10;
  }

  /* ── 3. TYPOGRAPHY ── */
  if (guidelines.typography) {
    ensureSpace(120);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(...THEME.accent);
    pdf.text('TYPOGRAPHY', MARGIN, y);
    y += 20;

    pdf.setFillColor(...THEME.card);
    const typoText = guidelines.typography.rationale || '';
    const ratLines = pdf.splitTextToSize(typoText, CONTENT_W - 30);
    const boxH = 60 + (ratLines.length * 12);
    pdf.roundedRect(MARGIN, y - 10, CONTENT_W, boxH, 8, 8, 'F');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(14);
    pdf.setTextColor(...THEME.title);
    pdf.text(`Primary: ${guidelines.typography.primaryFont}`, MARGIN + 15, y + 15);
    
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(12);
    pdf.setTextColor(...THEME.body);
    pdf.text(`Secondary: ${guidelines.typography.secondaryFont}`, MARGIN + 15, y + 35);

    pdf.setFontSize(9);
    pdf.setTextColor(...THEME.muted);
    pdf.text(ratLines, MARGIN + 15, y + 55);
    
    y += boxH + 20;
  }

  /* ── 4. LOGO USAGE ── */
  if (guidelines.logoUsage) {
    ensureSpace(60);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(...THEME.accent);
    pdf.text('LOGO USAGE RULES', MARGIN, y);
    y += 20;

    guidelines.logoUsage.forEach(rule => {
      const lines = pdf.splitTextToSize(`• ${rule}`, CONTENT_W - 20);
      ensureSpace(lines.length * 15);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(...THEME.body);
      pdf.text(lines, MARGIN + 10, y);
      y += lines.length * 15;
    });
    y += 20;
  }

  /* ── 5. BRAND VOICE ── */
  if (guidelines.brandVoice) {
    ensureSpace(80);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(...THEME.accent);
    pdf.text('BRAND VOICE & TONE', MARGIN, y);
    y += 20;

    // Tones
    let tx = MARGIN;
    (guidelines.brandVoice.tone || []).forEach(t => {
      const tw = pdf.getTextWidth(t) + 20;
      if (tx + tw > W - MARGIN) { tx = MARGIN; y += 22; ensureSpace(30); }
      pdf.setFillColor(...THEME.accent);
      pdf.roundedRect(tx, y - 12, tw, 18, 9, 9, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFont('helvetica', 'bold');
      pdf.text(t, tx + 10, y);
      tx += tw + 8;
    });
    y += 30;

    if (guidelines.brandVoice.examplePhrase) {
      const phrase = `"${guidelines.brandVoice.examplePhrase}"`;
      const pLines = pdf.splitTextToSize(phrase, CONTENT_W - 40);
      ensureSpace(pLines.length * 14 + 30);
      pdf.setFillColor(...THEME.card);
      pdf.roundedRect(MARGIN, y - 10, CONTENT_W, pLines.length * 14 + 20, 8, 8, 'F');
      pdf.setFont('helvetica', 'italic');
      pdf.setFontSize(11);
      pdf.setTextColor(...THEME.title);
      pdf.text(pLines, MARGIN + 20, y + 5);
      y += pLines.length * 14 + 30;
    }
  }

  /* ── 6. DO'S & DON'TS ── */
  if (guidelines.dosAndDonts) {
    ensureSpace(150);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(...THEME.accent);
    pdf.text("DO'S & DON'TS", MARGIN, y);
    y += 20;

    const columnW = (CONTENT_W - 20) / 2;
    const dos = guidelines.dosAndDonts.dos || [];
    const donts = guidelines.dosAndDonts.donts || [];

    // Calculate needed height for both columns to draw boxes
    const dosWrapped = dos.map(d => pdf.splitTextToSize(`+ ${d}`, columnW - 20));
    const dontsWrapped = donts.map(d => pdf.splitTextToSize(`- ${d}`, columnW - 20));
    
    const dosH = dosWrapped.reduce((acc, curr) => acc + curr.length * 13 + 5, 30);
    const dontsH = dontsWrapped.reduce((acc, curr) => acc + curr.length * 13 + 5, 30);
    const sectionH = Math.max(dosH, dontsH);

    ensureSpace(sectionH + 20);

    // Dos box
    pdf.setFillColor(isDark ? 20 : 230, isDark ? 50 : 250, isDark ? 30 : 240);
    pdf.roundedRect(MARGIN, y, columnW, sectionH, 8, 8, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(isDark ? 100 : 20, isDark ? 255 : 100, isDark ? 150 : 50);
    pdf.text('DO', MARGIN + 15, y + 20);
    
    let dy = y + 40;
    dosWrapped.forEach(lines => {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.text(lines, MARGIN + 15, dy, { align: 'left' });
      dy += lines.length * 13 + 5;
    });

    // Donts box
    pdf.setFillColor(isDark ? 60 : 255, isDark ? 20 : 240, isDark ? 20 : 240);
    pdf.roundedRect(MARGIN + columnW + 20, y, columnW, sectionH, 8, 8, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(isDark ? 255 : 150, isDark ? 150 : 20, isDark ? 150 : 20);
    pdf.text("DON'T", MARGIN + columnW + 35, y + 20);
    
    let dny = y + 40;
    dontsWrapped.forEach(lines => {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.text(lines, MARGIN + columnW + 35, dny, { align: 'left' });
      dny += lines.length * 13 + 5;
    });

    y += sectionH + 40;
  }

  drawFooter();
  pdf.save(`${brandName.replace(/\s+/g, '_')}_Brand_Guidelines.pdf`);
}

/* ── Main Component ────────────────────────────────────────────── */
const BrandGuidelinesModal = ({ logo, onClose, brandContext }) => {
  const { user } = useAuth();
  const { isDark } = useTheme();
  // We prioritize the logo object's metadata for state isolation
  const brandName = logo?.brand_name || 'Brand'; 
  const [guidelines, setGuidelines] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [pdfLoading, setPdfLoading] = useState(false);

  useEffect(() => { fetchGuidelines(); }, []);

  const getToken = async () => user?.getIdToken ? await user.getIdToken() : null;

  const fetchGuidelines = async () => {
    setLoading(true); setError(null);
    try {
      const token = await getToken();
      if (logo?.id) {
        try {
          const cached = await axios.get(`${API}/brands/guidelines/${logo.id}`, { headers: { Authorization: `Bearer ${token}` } });
          if (cached.data?.data?.guidelines) { setGuidelines(cached.data.data.guidelines); return; }
        } catch (_) { /* fall through */ }
      }
      const res = await axios.post(`${API}/brands/guidelines/generate`, {
        brandName: logo?.brand_name || 'My Brand',
        industry: logo?.industry || '',
        colors: logo?.colors?.primary || '',
        logoId: logo?.id || null,
        aiPrompt: logo?.prompt || '',
      }, { headers: { Authorization: `Bearer ${token}` } });
      setGuidelines(res.data.data.guidelines);
    } catch (e) { setError('Failed to generate guidelines. Please try again.'); }
    finally { setLoading(false); }
  };

  const downloadPDF = async () => {
    if (!guidelines) return;
    setPdfLoading(true);
    try {
      await buildPDF(guidelines, logo, brandContext, isDark);
    } catch (err) {
      console.error('PDF generation failed:', err);
      alert('PDF generation failed. Please try again.');
    } finally { setPdfLoading(false); }
  };

  return (
    <div className="modal-overlay" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal-panel">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-[var(--border-color)] brand-gradient flex-shrink-0">
          <div>
            <h2 className="text-xl font-bold text-white">Brand Guidelines</h2>
            <p className="text-sm text-purple-200 mt-0.5">{brandName}</p>
          </div>
          <div className="flex gap-2">
            <button onClick={downloadPDF} disabled={!guidelines || pdfLoading}
              className="px-4 py-2 text-sm font-semibold rounded-xl bg-white/20 text-white hover:bg-white/30 transition disabled:opacity-40 flex items-center gap-2">
              {pdfLoading
                ? <><span className="w-3 h-3 border-2 border-white/60 border-t-white rounded-full animate-spin" />Generating...</>
                : `⬇ Download ${isDark ? 'Dark' : 'Light'} PDF`}
            </button>
            <button onClick={onClose} className="w-9 h-9 flex items-center justify-center rounded-xl bg-white/20 text-white hover:bg-white/30 transition text-lg">×</button>
          </div>
        </div>

        {/* Body */}
        <div className="p-6 overflow-y-auto" style={{ maxHeight: 'calc(90vh - 100px)' }}>
          {loading && (
            <div className="flex flex-col items-center justify-center py-16">
              <div className="w-12 h-12 rounded-full border-4 border-purple-500 border-t-transparent animate-spin mb-4" />
              <p style={{ color: 'var(--text-secondary)' }}>Generating your brand guidelines...</p>
            </div>
          )}
          {error && (
            <div className="text-center py-12">
              <p className="text-red-400 mb-4">{error}</p>
              <button onClick={fetchGuidelines} className="px-6 py-2 rounded-xl brand-gradient text-white text-sm font-semibold">Try Again</button>
            </div>
          )}
          {guidelines && (
            <div className="grid md:grid-cols-2 gap-6">
              {/* Left column */}
              <div>
                {logo?.logo_url && (
                  <div className="mb-5 p-4 rounded-2xl glass-card flex justify-center">
                    <img src={logo.logo_url} alt="Logo" className="h-20 object-contain" crossOrigin="anonymous" />
                  </div>
                )}
                <Section title="Color Palette">
                  {guidelines.colorPalette && Object.values(guidelines.colorPalette).map((c, i) => (
                    <ColorSwatch key={i} hex={c.hex} name={c.name} usage={c.usage} />
                  ))}
                </Section>
                <Section title="Typography">
                  <div className="p-4 rounded-xl glass-card">
                    <p className="font-bold text-sm mb-1" style={{ color: 'var(--text-primary)' }}>
                      Primary: {guidelines.typography?.primaryFont}
                    </p>
                    <p className="text-sm mb-2" style={{ color: 'var(--text-secondary)' }}>
                      Secondary: {guidelines.typography?.secondaryFont}
                    </p>
                    <p className="text-xs leading-relaxed" style={{ color: 'var(--text-muted)' }}>
                      {guidelines.typography?.rationale}
                    </p>
                  </div>
                </Section>
              </div>

              {/* Right column */}
              <div>
                <Section title="Logo Usage">
                  <ul className="space-y-2">
                    {guidelines.logoUsage?.map((r, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm" style={{ color: 'var(--text-secondary)' }}>
                        <span className="text-purple-400 mt-0.5 flex-shrink-0">✓</span>{r}
                      </li>
                    ))}
                  </ul>
                </Section>
                <Section title="Brand Voice">
                  <div className="flex flex-wrap gap-2 mb-3">
                    {guidelines.brandVoice?.tone?.map((t, i) => (
                      <span key={i} className="px-3 py-1 rounded-full brand-gradient text-white text-xs font-semibold">{t}</span>
                    ))}
                  </div>
                  {guidelines.brandVoice?.examplePhrase && (
                    <div className="p-3 rounded-xl glass-card italic text-sm" style={{ color: 'var(--text-secondary)' }}>
                      "{guidelines.brandVoice.examplePhrase}"
                    </div>
                  )}
                </Section>
                <Section title="Do's & Don'ts">
                  <div className="grid grid-cols-2 gap-3">
                    <div className="p-3 rounded-xl" style={{ background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.2)' }}>
                      <p className="text-xs font-bold text-green-400 mb-2">DO</p>
                      {guidelines.dosAndDonts?.dos?.map((d, i) => (
                        <p key={i} className="text-xs mb-1" style={{ color: 'var(--text-secondary)' }}>+ {d}</p>
                      ))}
                    </div>
                    <div className="p-3 rounded-xl" style={{ background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.2)' }}>
                      <p className="text-xs font-bold text-red-400 mb-2">DON'T</p>
                      {guidelines.dosAndDonts?.donts?.map((d, i) => (
                        <p key={i} className="text-xs mb-1" style={{ color: 'var(--text-secondary)' }}>- {d}</p>
                      ))}
                    </div>
                  </div>
                </Section>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default BrandGuidelinesModal;
