import { useState, useEffect } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import api from "../services/api";
import jsPDF from "jspdf";

// Resolve logo URL — prepend API base if it's a relative path
const resolveUrl = (url) => {
  if (!url || url === "processing...") return "/brandybot_icon.png";
  if (url.startsWith("data:") || url.startsWith("http")) return url;
  const base = (import.meta.env.VITE_API_URL || "http://localhost:5000/api").replace("/api", "");
  return `${base}${url}`;
};

export default function BrandGuidelines() {
  const location = useLocation();
  const navigate = useNavigate();

  const passedProfile = location.state?.brandProfile || {};
  const passedLogoUrl = location.state?.logoUrl || null;
  const brandName = passedProfile.brandName || "Brand";
  const logoUrl = resolveUrl(passedLogoUrl);

  const [guidelines, setGuidelines] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (brandName && brandName !== "Brand") {
      generateGuidelines();
    }
  }, []);

  const generateGuidelines = async () => {
    setIsGenerating(true);
    setError(null);
    try {
      // Use the stateless endpoint — no brand creation needed
      const res = await axios.post(
        `${import.meta.env.VITE_API_URL || "http://localhost:5000/api"}/brands/guidelines/generate`,
        {
          brandName: passedProfile.brandName,
          industry: passedProfile.industry || "",
          targetAudience: passedProfile.targetAudience || "",
          personality: passedProfile.personality || "",
          colors: passedProfile.colors || "",
          logoUrl: passedLogoUrl || "",
          aiPrompt: passedProfile.aiPrompt || "", // Added aiPrompt
        },
        {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`
          }
        }
      );
      setGuidelines(res.data.data.guidelines);
    } catch (err) {
      console.error("Guidelines error:", err);
      setError("Could not generate brand guidelines. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF("p", "pt", "a4");
    let y = 60;
    doc.setFontSize(22); doc.text(`${brandName} — Brand Guidelines`, 40, y); y += 30;
    doc.setFontSize(11); doc.setTextColor(120); doc.text("Generated by BrandyBot AI", 40, y); y += 30;
    doc.setTextColor(0);

    const addSection = (title, items) => {
      if (y > 720) { doc.addPage(); y = 40; }
      doc.setFontSize(14); doc.setFont(undefined, "bold"); doc.text(title, 40, y); y += 20;
      doc.setFontSize(11); doc.setFont(undefined, "normal");
      (Array.isArray(items) ? items : [items]).forEach(line => {
        const wrapped = doc.splitTextToSize(String(line), 500);
        doc.text(wrapped, 50, y); y += wrapped.length * 14 + 4;
        if (y > 730) { doc.addPage(); y = 40; }
      });
      y += 10;
    };

    if (guidelines) {
      if (guidelines.logoUsage) addSection("Logo Usage", guidelines.logoUsage);
      if (guidelines.brandVoice?.guidelines) addSection("Brand Voice", guidelines.brandVoice.guidelines);
      if (guidelines.typography) addSection("Typography", [`Primary: ${guidelines.typography.primaryFont}`, `Secondary: ${guidelines.typography.secondaryFont}`, guidelines.typography.rationale]);
      if (guidelines.dosAndDonts) { addSection("Do's", guidelines.dosAndDonts.dos); addSection("Don'ts", guidelines.dosAndDonts.donts); }
      if (guidelines.imagery) addSection("Imagery Style", guidelines.imagery);
    }
    doc.save(`${brandName}_Brand_Guidelines.pdf`);
  };

  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-br from-slate-50 via-purple-50 to-blue-50">
      {/* Header */}
      <header className="p-5 flex items-center gap-3 shadow-lg" style={{ background: "linear-gradient(90deg, #7C3AED, #3B82F6)" }}>
        <Link to="/"><img src="/brandybot_icon.png" className="h-10 w-10 rounded-full shadow ring-2 ring-white/30" alt="BrandyBot" /></Link>
        <div>
          <h1 className="text-xl font-bold text-white">Brand Guidelines</h1>
          <p className="text-purple-200 text-xs">AI-Generated for {brandName}</p>
        </div>
      </header>

      {/* Hero */}
      <div className="bg-white border-b border-gray-100 shadow-sm">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 flex flex-col sm:flex-row items-start sm:items-center gap-4">
          <img src={logoUrl} alt={brandName} className="h-20 w-20 rounded-2xl object-contain bg-white p-2 border border-gray-100 shadow flex-shrink-0"
            onError={(e) => { e.target.src = "/brandybot_icon.png"; }} />
          <div>
            <h2 className="text-2xl sm:text-3xl font-bold text-gray-900">{brandName}</h2>
            <p className="text-gray-500 mt-1 text-sm">{passedProfile.industry}{passedProfile.personality ? ` · ${passedProfile.personality}` : ""}</p>
            {guidelines?.colorPalette && (
              <div className="flex gap-2 mt-3">
                {Object.values(guidelines.colorPalette).slice(0, 4).map((c, i) => (
                  <div key={i} style={{ background: c.hex }} className="w-8 h-8 rounded-lg border border-gray-200 shadow-sm cursor-help" title={`${c.name}: ${c.hex}`} />
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 max-w-4xl mx-auto w-full px-4 sm:px-6 py-6 space-y-5 pb-28">

        {/* No brand passed */}
        {(!brandName || brandName === "Brand") && !isGenerating && (
          <div className="bg-white rounded-3xl p-12 shadow-lg text-center border border-gray-100">
            <p className="text-gray-500 mb-4">No brand profile found. Please generate a logo first.</p>
            <Link to="/logo_generator" className="px-6 py-3 text-white rounded-xl font-semibold text-sm inline-block" style={{ background: "linear-gradient(90deg, #7C3AED, #3B82F6)" }}>
              Go to Logo Generator
            </Link>
          </div>
        )}

        {/* Loading */}
        {isGenerating && (
          <div className="bg-white rounded-3xl p-12 shadow-lg text-center border border-purple-50">
            <div className="flex justify-center gap-2 mb-4">
              {[0, 150, 300].map(d => <div key={d} className="w-3 h-3 bg-purple-400 rounded-full animate-bounce" style={{ animationDelay: `${d}ms` }} />)}
            </div>
            <p className="text-gray-600 font-medium">Generating AI guidelines for <strong>{brandName}</strong>...</p>
            <p className="text-gray-400 text-sm mt-1">~10 seconds</p>
          </div>
        )}

        {/* Error */}
        {error && !isGenerating && (
          <div className="bg-red-50 border border-red-200 rounded-2xl p-6 text-center">
            <p className="text-red-700">{error}</p>
            <button onClick={generateGuidelines} className="mt-4 px-6 py-2 bg-red-600 text-white rounded-xl hover:bg-red-700 transition text-sm font-medium">Try Again</button>
          </div>
        )}

        {/* Guidelines cards */}
        {guidelines && !isGenerating && (<>
          {guidelines.logoUsage && (
            <GuidelineSection title="Logo Usage" icon="🖼️" color="purple">
              <ul className="space-y-2">{guidelines.logoUsage.map((r, i) => <li key={i} className="flex gap-2 text-gray-700 text-sm"><span className="text-purple-400 mt-0.5 flex-shrink-0">•</span>{r}</li>)}</ul>
            </GuidelineSection>
          )}
          {guidelines.colorPalette && (
            <GuidelineSection title="Color Palette" icon="🎨" color="blue">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                {Object.entries(guidelines.colorPalette).map(([role, c]) => (
                  <div key={role} className="flex items-center gap-3 p-3 bg-gray-50 rounded-xl border border-gray-100">
                    <div style={{ background: c.hex }} className="w-12 h-12 rounded-xl border border-gray-200 shadow-sm flex-shrink-0" />
                    <div><p className="font-semibold text-gray-800 capitalize text-sm">{role}</p><p className="text-xs text-gray-500">{c.hex}</p><p className="text-xs text-gray-400">{c.name}</p></div>
                  </div>
                ))}
              </div>
            </GuidelineSection>
          )}
          {guidelines.typography && (
            <GuidelineSection title="Typography" icon="✍️" color="green">
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="p-4 bg-gray-50 rounded-xl border border-gray-100">
                  <p className="text-xs text-gray-400 uppercase font-semibold mb-1">Primary Font</p>
                  <p style={{ fontFamily: guidelines.typography.primaryFont }} className="text-2xl font-bold text-gray-800">{guidelines.typography.primaryFont}</p>
                  <p className="text-xs text-gray-500 mt-1">Weight: {guidelines.typography.headingWeight}</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-xl border border-gray-100">
                  <p className="text-xs text-gray-400 uppercase font-semibold mb-1">Secondary Font</p>
                  <p style={{ fontFamily: guidelines.typography.secondaryFont }} className="text-xl text-gray-800">{guidelines.typography.secondaryFont}</p>
                  <p className="text-xs text-gray-500 mt-1">Weight: {guidelines.typography.bodyWeight}</p>
                </div>
              </div>
              {guidelines.typography.rationale && <p className="mt-3 text-gray-600 text-sm">{guidelines.typography.rationale}</p>}
            </GuidelineSection>
          )}
          {guidelines.brandVoice && (
            <GuidelineSection title="Brand Voice & Tone" icon="🗣️" color="yellow">
              {guidelines.brandVoice.tone && (
                <div className="flex flex-wrap gap-2 mb-3">
                  {guidelines.brandVoice.tone.map((t, i) => <span key={i} className="px-3 py-1 bg-yellow-100 text-yellow-800 rounded-full text-sm font-medium capitalize">{t}</span>)}
                </div>
              )}
              {guidelines.brandVoice.guidelines && <ul className="space-y-2 mb-3">{guidelines.brandVoice.guidelines.map((g, i) => <li key={i} className="flex gap-2 text-gray-700 text-sm"><span className="text-yellow-400 flex-shrink-0">•</span>{g}</li>)}</ul>}
              {guidelines.brandVoice.examplePhrase && <blockquote className="border-l-4 border-yellow-400 pl-4 italic text-gray-600 text-sm">"{guidelines.brandVoice.examplePhrase}"</blockquote>}
            </GuidelineSection>
          )}
          {guidelines.dosAndDonts && (
            <GuidelineSection title="Do's & Don'ts" icon="✅" color="red">
              <div className="grid sm:grid-cols-2 gap-6">
                <div><p className="font-semibold text-green-700 mb-2 text-sm">✅ Do's</p><ul className="space-y-1">{guidelines.dosAndDonts.dos?.map((d, i) => <li key={i} className="flex gap-2 text-gray-700 text-sm"><span className="text-green-500 flex-shrink-0">✓</span>{d}</li>)}</ul></div>
                <div><p className="font-semibold text-red-700 mb-2 text-sm">❌ Don'ts</p><ul className="space-y-1">{guidelines.dosAndDonts.donts?.map((d, i) => <li key={i} className="flex gap-2 text-gray-700 text-sm"><span className="text-red-500 flex-shrink-0">✗</span>{d}</li>)}</ul></div>
              </div>
            </GuidelineSection>
          )}
          {guidelines.imagery && (
            <GuidelineSection title="Imagery Style" icon="🖼️" color="indigo">
              <ul className="space-y-2">{guidelines.imagery.map((r, i) => <li key={i} className="flex gap-2 text-gray-700 text-sm"><span className="text-indigo-400 flex-shrink-0">•</span>{r}</li>)}</ul>
            </GuidelineSection>
          )}
        </>)}
      </div>

      {/* Footer */}
      <footer className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 shadow-2xl">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-3 flex flex-wrap gap-2 justify-end">
          <button onClick={handleDownloadPDF} disabled={!guidelines} className="px-4 py-2 text-white rounded-xl text-sm font-semibold hover:opacity-90 transition disabled:opacity-40" style={{ background: "linear-gradient(90deg,#7C3AED,#3B82F6)" }}>
            ⬇ Download PDF
          </button>
          <Link to="/mockup_generator" state={{ logoUrl: passedLogoUrl, brandName }} className="px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition">
            👕 Mockups
          </Link>
        </div>
      </footer>
    </div>
  );
}

function GuidelineSection({ title, icon, color, children }) {
  const colorMap = { purple: "from-purple-50 border-purple-100", blue: "from-blue-50 border-blue-100", green: "from-green-50 border-green-100", yellow: "from-yellow-50 border-yellow-100", red: "from-red-50 border-red-100", indigo: "from-indigo-50 border-indigo-100" };
  return (
    <div className="bg-white rounded-2xl shadow border border-gray-100 overflow-hidden hover:shadow-md transition">
      <div className={`bg-gradient-to-r ${colorMap[color] || colorMap.purple} to-white px-5 py-4 border-b flex items-center gap-2`}>
        <span className="text-lg">{icon}</span>
        <h2 className="text-base font-bold text-gray-900">{title}</h2>
      </div>
      <div className="px-5 py-4">{children}</div>
    </div>
  );
}
